In [1]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a=[1,2,3]
b=np.array([4,5,6])
t_a=torch.tensor(a)
t_b=torch.from_numpy(b)
print(a)
print(b)
print(t_a)
print(t_b)


[1, 2, 3]
[4 5 6]
tensor([1, 2, 3])
tensor([4, 5, 6])


In [3]:
t_a.shape

torch.Size([3])

In [4]:
t_ones=torch.ones(2,3)
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
rand_tensor=torch.rand(2,3)
print(rand_tensor)

tensor([[0.5275, 0.7840, 0.1179],
        [0.0753, 0.5696, 0.9660]])


In [6]:
t_a.dtype


torch.int64

In [8]:
t_a_new=t_a.to(torch.int64)
t_a_new.shape
t_a_new.dtype

torch.int64

In [9]:
t=torch.rand(3, 5)
t_tr=torch.transpose(t,0,1)
print(t.shape,' --> ',t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


In [10]:
t1=2*torch.rand(5,2)-1
t2=torch.normal(mean=0,std=1,size=(5,2))
t3=t1*t2
print(t3)


tensor([[-0.1521, -0.6653],
        [ 0.5244, -0.4380],
        [ 0.1234,  0.6596],
        [ 0.0713, -0.1793],
        [-0.0404, -0.0814]])


In [11]:
t4=torch.mean(t1,axis=0)
print(t4)

tensor([-0.5369, -0.1499])


In [13]:
t5=torch.matmul(t1,torch.transpose(t2,0,1))
print(t5)

tensor([[-8.1738e-01,  1.6218e+00, -7.1789e-01,  1.4787e-01,  3.3686e-01],
        [-8.3094e-01,  8.6338e-02, -5.3244e-01,  1.1324e-01,  4.4111e-01],
        [ 1.2369e+00, -5.3138e-02,  7.8301e-01, -1.6677e-01, -6.6135e-01],
        [ 1.3256e+00,  2.9238e+00,  4.6265e-01, -1.0799e-01, -8.9703e-01],
        [ 2.3735e-03,  1.9084e+00, -2.3959e-01,  4.4978e-02, -1.2179e-01]])


In [15]:
t=torch.rand(6)
print(t)
t_split=torch.chunk(t,3)
[item.numpy() for item in t_split]


tensor([0.2510, 0.3990, 0.2376, 0.9151, 0.2385, 0.5418])


[array([0.2509508, 0.3990308], dtype=float32),
 array([0.23764688, 0.9150907 ], dtype=float32),
 array([0.23849499, 0.5417502 ], dtype=float32)]

In [22]:
t = torch.rand(6)
print(t)
t_split = torch.split(t, [3, 2, 1])
[item.numpy() for item in t_split]


tensor([0.3473, 0.6348, 0.0044, 0.8083, 0.5622, 0.0375])


[array([0.3472582 , 0.6348459 , 0.00435197], dtype=float32),
 array([0.808253  , 0.56218183], dtype=float32),
 array([0.03749382], dtype=float32)]

In [21]:
a=torch.ones(3)
b=torch.zeros(3)
c=torch.cat([a,b],axis=0)
print(c)

tensor([1., 1., 1., 0., 0., 0.])


In [23]:
s=torch.stack([a,b],axis=1)
print(s)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])
