In [2]:
import torch
from torch.utils.data import DataLoader
t=torch.arange(6,dtype=torch.float32)
data_loader=DataLoader(t)

In [3]:
for i in data_loader:
    print(i)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [4]:
data_loader=DataLoader(t,batch_size=3,drop_last=False)
for i, batch in enumerate(data_loader,1):
    print(f'batch {i}:', batch)


batch 1: tensor([0., 1., 2.])
batch 2: tensor([3., 4., 5.])


In [5]:
torch.manual_seed(1)
t_x=torch.rand([4,3],dtype=torch.float32)
t_y=torch.arange(4)

In [6]:
from torch.utils.data import Dataset
class JointDataset(Dataset):
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __len__(self):
        return len(self.x)
    def __getitem__(self,idx):
        return self.x[idx],self.y[idx]



In [7]:
join_dataset=JointDataset(t_x,t_y)

In [8]:
for arr in join_dataset:
    print(' x: ', arr[0], ' y: ', arr[1])

 x:  tensor([0.7576, 0.2793, 0.4031])  y:  tensor(0)
 x:  tensor([0.7347, 0.0293, 0.7999])  y:  tensor(1)
 x:  tensor([0.3971, 0.7544, 0.5695])  y:  tensor(2)
 x:  tensor([0.4388, 0.6387, 0.5247])  y:  tensor(3)
